name: Release ARM64

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release tag'
        required: true

jobs:
  build-deb-package:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Rust with cross compiliation
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
    - name: Install builders
      run: cargo install cargo-deb
    - name: Build Debian package
      run: |
        cargo deb --target=aarch64-unknown-linux-gnu -p rcp
        cargo deb --target=aarch64-unknown-linux-gnu -p rlink
        cargo deb --target=aarch64-unknown-linux-gnu -p rrm
        cargo deb --target=aarch64-unknown-linux-gnu -p rcmp
        cargo deb --target=aarch64-unknown-linux-gnu -p filegen
        zip rcp-deb-arm64-${{ github.event.release.tag_name }}.zip target/debian/*.deb
        echo $(pwd)/rcp-deb-arm64-${{ github.event.release.tag_name }}
        ls -ld $(pwd)/rcp-deb-arm64-${{ github.event.release.tag_name }}*
    - name: Upload to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./rcp-deb-arm64-${{ github.event.release.tag_name }}.zip
        asset_name: rcp-deb-arm64-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip

  build-rpm-package:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Rust with cross compiliation
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
    - name: Install builders
      run: cargo install cargo-generate-rpm
    - name: Build RPM package
      run: |
        cargo build --release --target=aarch64-unknown-linux-gnu
        cargo generate-rpm -p rcp
        cargo generate-rpm -p rlink
        cargo generate-rpm -p rrm
        cargo generate-rpm -p rcmp
        cargo generate-rpm -p filegen
        zip rcp-rpm-arm64-${{ github.event.release.tag_name }}.zip target/generate-rpm/*.rpm
        echo $(pwd)/rcp-rpm-arm64-${{ github.event.release.tag_name }}
        ls -ld $(pwd)/rcp-rpm-arm64-${{ github.event.release.tag_name }}*
    - name: Upload to GitHub Release
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./rcp-rpm-arm64-${{ github.event.release.tag_name }}.zip
        asset_name: rcp-rpm-arm64-${{ github.event.release.tag_name }}.zip
        asset_content_type: application/zip
